apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-worker-app
  labels:
    app: video-worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-worker-app
  template:
    metadata:
      name: video-worker-app
      labels:
        app: video-worker-app
    spec:
      containers:
        - name: video-worker-app
          image: video-worker-app
          imagePullPolicy: Always
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: secret-access-key
          - name: AWS_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: account-id
          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: access-session-token
          - name: AWS_REGION
            value: us-east-1
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      restartPolicy: Always
